[package]
name = "ascentexample1"
version = "0.1.0"
edition = "2021"

[dependencies]
ascent = "0.6.0"
stopwatch = "0.0.7"
bencher = "0.1.5"
derive_more = "0.99.16"
itertools = "0.12"
quote = "1.0"
arrayvec = "0.7"
const-fnv1a-hash = "1.0.1"
rand = "0.8.5"

[dev-dependencies]
rand = "0.8.5"